### PR TITLE
Database Performance Audit

### PR DESCRIPTION
**Pull request by sntgopl**
# Pull Request Review

### - Run `EXPLAIN ANALYZE` on three selected queries. 

`SELECT COUNT(*) FROM visits where animal_id = 4;`
Screenshot 2023-05-08 at 17 24 45

`SELECT * FROM visits where vet_id = 2;`
Screenshot 2023-05-08 at 17 25 13

`SELECT * FROM owners where email = 'owner_18327@mail.com';`
Screenshot 2023-05-08 at 17 25 42

# INDEX CREATION

## First query result:
Screenshot 2023-05-08 at 17 37 50

## Second query result:
Screenshot 2023-05-08 at 17 53 08

## Third query result:
Screenshot 2023-05-08 at 17 55 51

Please let us know if there's anything else we should try to increase performance on our project.

Thank you.

Regards.

### CODE REVIEW

**Review by mukhammadrizooff — COMMENTED** [review]
Hi @jaimevillegas, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, and your team members should participate in this project because this project is to complete a group!

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by mukhammadrizooff** [comment]
- `[OPTIONAL OPINION]`

image

**Comment by sntgopl** [comment]
Hello @mukhammadrizooff. Thank you for your time. Just to clear out, I'm not Jaime Villegas, I actually don't know why his name appeared as he was my morning partner last week and he is not even a collaborator on this project.

I would like to set clear that we worked on this project the three of us together, but the changes in the vscode were little and donde by me, so I don't know how they could commit on this pull request to submit again.

Last of all, I would like to ask for a suggestion to solve this last query that still takes too long. We've tried creating an index in ascending and descending order but neither improved much. If you could give us a hint on how to solve it in a different way. I was thinking maybe create a new table but that would change the query also.

Thank you for your time and attention.

Regards
Santiago.

**Comment by sntgopl** [comment]
# Pull Request Review

## In this milestone we, @Cabraham1 and @kkolade, have:

### - Added a new column to the owner's table with the name 'email'.
### - Insert into visits and owners table new data.
### - Run EXPLAIN ANALYZE on three selected queries.

## SELECT COUNT(*) FROM visits where animal_id = 4;
Screenshot 2023-05-08 at 17 24 45

## SELECT * FROM visits where vet_id = 2;
Screenshot 2023-05-08 at 17 25 13

## SELECT * FROM owners where email = 'owner_18327@mail.com';
Screenshot 2023-05-08 at 17 25 42

# INDEX CREATION

## First query result:
Screenshot 2023-05-08 at 17 37 50

## Second query result:
Screenshot 2023-05-08 at 19 48 42

## Third query result:
Screenshot 2023-05-08 at 17 55 51


Please let us know if there's anything else we should try to increase performance on our project.

Thank you.

Regards.

**Review by bobb-Rob — COMMENTED** [review]
Hi team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has not used [GitFlow ](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md) correctly, we expected the pull request to compare between `dev` or `develop` branch and the feature branch. Please fix this. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Pull request closed without merging**
